### PR TITLE
Swap call and send button to increase UX

### PR DESCRIPTION
**Pull request by andir**
It is alot easier to click on a button on the right edge of the screen
then clicking on a button between the textarea and the voice call
button.

This should help with reducing the amount of unwanted phone calls
started from the mobile app.

### CODE REVIEW

**Comment by ylecollen** [comment]
You should submit your idea to https://vector.im/beta/#/room/#vector-feedback:matrix.org.

We have to keep the same UI on both mobile clients.

The webclient already has the buttons in the order you expect.

**Comment by andir** [comment]
I tried to bring that topic up but seems rather challenging given the traffic in the channel. I could just provide a similar PR for iOS but I can't test nor compile it...

**Comment by ara4n** [comment]
I agree with @andir on this - @ylecollen, @giomfo - let's switch them over on both iOS & Android.

**Comment by 4nd3r** [comment]
#395 ?

**Comment by ylecollen** [comment]
The call button is hidden when there is an edited text like 4nd3r said.

**Comment by ylecollen** [comment]
screenshot_2016-09-20-11-09-15
screenshot_2016-09-20-11-09-27

**Pull request closed without merging**
